# zerotopandas

Use the "Run" button to execute the code.

In [2]:
!pip install jovian --upgrade --quiet

In [5]:
import jovian

In [6]:
# Execute this to save new versions of the notebook
jovian.commit(project="zerotopandas")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "heduinravell/zerotopandas" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/heduinravell/zerotopandas


'https://jovian.ai/heduinravell/zerotopandas'

In [8]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [9]:
 !pip install numpy

In [13]:
import numpy as np

In [14]:
kanto = np.array([73,67,43])

In [15]:
weights = np.array([w1, w2, w3])

In [16]:
type(kanto)

numpy.ndarray

In [17]:
type(weights)

numpy.ndarray

In [20]:
print(np.dot(kanto, weights))

56.8


In [22]:
help(np.cross)

Help on function cross in module numpy:

cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
    Return the cross product of two (arrays of) vectors.
    
    The cross product of `a` and `b` in :math:`R^3` is a vector perpendicular
    to both `a` and `b`.  If `a` and `b` are arrays of vectors, the vectors
    are defined by the last axis of `a` and `b` by default, and these axes
    can have dimensions 2 or 3.  Where the dimension of either `a` or `b` is
    2, the third component of the input vector is assumed to be zero and the
    cross product calculated accordingly.  In cases where both input vectors
    have dimension 2, the z-component of the cross product is returned.
    
    Parameters
    ----------
    a : array_like
        Components of the first vector(s).
    b : array_like
        Components of the second vector(s).
    axisa : int, optional
        Axis of `a` that defines the vector(s).  By default, the last axis.
    axisb : int, optional
        Axis of `b` that

In [24]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [26]:
import jovian

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "heduinravell/zerotopandas" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/heduinravell/zerotopandas


'https://jovian.ai/heduinravell/zerotopandas'

In [33]:
climate_data = np.array([[73, 67, 43],[91,88,64],[87,134,58],[102,43, 37],[69,96,70]])

In [36]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [38]:
climate_data.shape

(5, 3)

In [40]:
weights

array([0.3, 0.2, 0.5])

In [42]:
weights.shape

(3,)

In [56]:
arr3 = np.array([
    [[11,12,13],
     [13,14,15]],
    
    [[15,16,17],
     [17,18,19]]])

In [60]:
arr3.shape

(2, 2, 3)

In [62]:
arr3f = np.array([
    [[11,12,13],
     [13,14,15]],
    
    [[15,16,17],
     [17,18,19.9]]])

In [64]:
arr3f.dtype  #float vs int

dtype('float64')

In [58]:
weights.dtype

dtype('float64')

In [59]:
climate_data.dtype

dtype('int64')

In [66]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [68]:
weights

array([0.3, 0.2, 0.5])

In [70]:
# matmul: dotprod for matrices . vector is the operator @
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [72]:
# operator @ is np.matmul
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [73]:
# CSV data files
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f95949d8850>)

In [86]:
climate_data = np.genfromtxt('climate.txt', delimiter=',',skip_header=1)

In [87]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [88]:
climate_data.shape

(10000, 3)

In [90]:
yields = climate_data @ weights

In [92]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [94]:
yields.shape

(10000,)

In [100]:
# add new column: result as 4th column, must match dimensions
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis=1)

In [102]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [104]:
climate_results.shape

(10000, 4)

In [124]:
%%time
#no delimiter: tab as default
#comments: 1st character on header
np.savetxt('climate_results.txt', 
          climate_results,
          fmt='%.2f',
          header='temperature,rainfall,humidity,yields_apples',
          delimiter=',',
          comments='')

CPU times: user 23.1 ms, sys: 867 µs, total: 23.9 ms
Wall time: 24.1 ms


In [126]:
jovian.commit( )

<IPython.core.display.Javascript object>

[jovian] Updating notebook "heduinravell/zerotopandas" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/heduinravell/zerotopandas


'https://jovian.ai/heduinravell/zerotopandas'

In [128]:
# array comparison
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [131]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [134]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [136]:
# count the number of true element-wise
(arr1 == arr2).sum()

3

In [138]:
# indexing, slicing
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [140]:
arr3.shape

(3, 2, 4)

In [142]:
arr3[1, 1, 2]

36.0

In [144]:
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [145]:
# standard matrices
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [146]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [148]:
# rand x randn
np.random.rand(5)

array([0.4559196 , 0.73932742, 0.85198779, 0.04309794, 0.30167382])

In [162]:
np.random.randn(4,5)

array([[-1.77520402,  0.70005133,  0.09843404,  1.61361003, -0.1505891 ],
       [ 0.33953866, -0.99529501, -2.50390123,  0.85687882, -0.78287259],
       [-0.38560111,  2.68253557,  1.19678263,  0.29888757, -0.84972568],
       [ 0.02870829,  0.17068576, -0.43519925,  0.65212085, -0.32231707]])

In [165]:
#fixed value
np.full([4,3],777)

array([[777, 777, 777],
       [777, 777, 777],
       [777, 777, 777],
       [777, 777, 777]])

In [172]:
np.arange(9,90,3)

array([ 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57,
       60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

In [175]:
np.arange(9,90,3).reshape(3,3,3)  
#np.arange(9,90,3).reshape(3,3,-1) can leave the last to be computed .reshape(3,3,-1) using -1

array([[[ 9, 12, 15],
        [18, 21, 24],
        [27, 30, 33]],

       [[36, 39, 42],
        [45, 48, 51],
        [54, 57, 60]],

       [[63, 66, 69],
        [72, 75, 78],
        [81, 84, 87]]])

In [176]:
np.linspace(3,27,9)  # 9 terms btw [3..27]

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [177]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "heduinravell/zerotopandas" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/heduinravell/zerotopandas


'https://jovian.ai/heduinravell/zerotopandas'